const VEHICLE_NAMES = {
    "ADMIRAL": "Admiral",
    "LANDSTAL": "Landstalker",
    "IDAHO": "Idaho",
    "STINGER": "Stinger",
    "LINERUN": "Linerunner",
    "PEREN": "Perennial",
    "SENTINEL": "Sentinel",
    "PATRIOT": "Patriot",
    "FIRETRUK": "Fire Truck",
    "TRASH": "Trashmaster",
    "STRETCH": "Stretch",
    "MANANA": "Manana",
    "INFERNUS": "Infernus",
    "BLISTA": "Blista",
    "PONY": "Pony",
    "MULE": "Mule",
    "CHEETAH": "Cheetah",
    "AMBULAN": "Ambulance",
    "FBICAR": "FBI Kuruma",
    "MOONBEAM": "Moonbeam",
    "ESPERANT": "Esperanto",
    "TAXI": "Taxi",
    "KURUMA": "Kuruma",
    "BOBCAT": "Bobcat",
    "MRWHOOP": "Mr. Whoopee",
    "BFINJECT": "BF Injection",
    "POLICE": "Police",
    "ENFORCER": "Enforcer",
    "SECURICA": "Securicar",
    "BANSHEE": "Banshee",
    "PREDATOR": "Predator",
    "BUS": "Bus",
    "RHINO": "Rhino",
    "BARRACKS": "Barracks OL",
    "TRAIN": "Train",
    "HELI": "Police Helicopter",
    "DODO": "Dodo",
    "COACH": "Coach",
    "CABBIE": "Cabbie",
    "STALLION": "Stallion",
    "RUMPO": "Rumpo",
    "RCBANDIT": "RC Bandit",
    "BELLYUP": "Belly Up",
    "MRWONGS": "Mr. Wong's",
    "MAFIA": "Mafia Sentinel",
    "YARDIE": "Yardie Lobo",
    "YAKUZA": "Yakuza Stinger",
    "DIABLOS": "Diablo Stallion",
    "COLUMB": "Cartel Cruiser",
    "HOODS": "Hoods Rumpo",
    "AIRTRAIN": "NPC Airliner",
    "DEADDODO": "NPC Dodo",
    "SPEEDER": "Speeder",
    "REEFER": "Reefer",
    "PANLANT": "Panlantic",
    "FLATBED": "Flatbed",
    "YANKEE": "Yankee",
    "BORGNINE": "Borgnine Cabbie"
};

export default VEHICLE_NAMES;