var APP_CONFIGS = {
	GTAIII: {
		METHOD: 'GET',
		DATA_URL: 'models/gta_iii.json',
		IMAGES_URL: 'img/vehicles/gta_iii',
		START_INDEX: 0,
		PARAMETER_NAMES: {
			id: 'Vehicle Id',
			mass: 'Mass',
			dimx: 'Dimension: X Axis',
			dimy: 'Dimension: Y Axis',
			dimz: 'Dimension: Z Axis',
			cmassx: 'Center of Mass: X Axis',
			cmassy: 'Center of Mass: Y Axis',
			cmassz: 'Center of Mass: Z Axis',
			persubmerged: 'Percent Submerged',
			tractionmult: 'Traction: Multiplier',
			tractionloss: 'Traction: Loss',
			tractionbias: 'Traction: Bias',
			numofgears: 'Number of Gears',
			velocity: 'Velocity',
			acceleration: 'Acceleration',
			drivetype: 'Drive Type',
			enginetype: 'Engine Type',
			deceleration: 'Deceleration',
			brakebias: 'Brake Bias',
			abs: 'ABS',
			steeringlock: 'Steering Lock',
			suspensionforce: 'Suspension: Force',
			suspensiondamping: 'Suspension: Damping',
			seatoffset: 'Seat Offset',
			collisiondamage: 'Collision Damage',
			value: 'Monetary Value',
			suspensionuplimit: 'Suspension: Upper Limit',
			suspensionlowlimit: 'Suspension: Lower Limit',
			suspensionbias: 'Suspension: Bias',
			flags: 'Flags',
			frontlights: 'Front Lights',
			rearlights: 'Rear Lights'
		},
		VEHICLE_NAMES: {
			'LANDSTAL': 'Landstalker',
			'IDAHO': 'Idaho',
			'STINGER': 'Stinger',
			'LINERUN': 'Linerunner',
			'PEREN': 'Perennial',
			'SENTINEL': 'Sentinel',
			'PATRIOT': 'Patriot',
			'FIRETRUK': 'Fire Truck',
			'TRASH': 'Trashmaster',
			'STRETCH': 'Stretch',
			'MANANA': 'Manana',
			'INFERNUS': 'Infernus',
			'BLISTA': 'Blista',
			'PONY': 'Pony',
			'MULE': 'Mule',
			'CHEETAH': 'Cheetah',
			'AMBULAN': 'Ambulance',
			'FBICAR': 'FBI Car',
			'MOONBEAM': 'Moonbeam',
			'ESPERANT': 'Esperanto',
			'TAXI': 'Taxi',
			'KURUMA': 'Kuruma',
			'BOBCAT': 'Bobcat',
			'MRWHOOP': 'Mr. Whoopie',
			'BFINJECT': 'BF Injection',
			'POLICE': 'Police',
			'ENFORCER': 'Enforcer',
			'SECURICA': 'Securicar',
			'BANSHEE': 'Banshee',
			'PREDATOR': 'Predator',
			'BUS': 'Bus',
			'RHINO': 'Rhino',
			'BARRACKS': 'Barracks OL',
			'TRAIN': 'Train',
			'HELI': 'Police Heli',
			'DODO': 'Dodo',
			'COACH': 'Coach',
			'CABBIE': 'Cabbie',
			'STALLION': 'Stallion',
			'RUMPO': 'Rumpo',
			'RCBANDIT': 'RC Bandit',
			'BELLYUP': 'Belly Up',
			'MRWONGS': 'Mr. Wong\'s',
			'MAFIA': 'Mafia Sentinel',
			'YARDIE': 'Yardie Lobo',
			'YAKUZA': 'Yakuza Stinger',
			'DIABLOS': 'Diablo Stallion',
			'COLUMB': 'Cartel Cruiser',
			'HOODS': 'Hoods Rumpo',
			'AIRTRAIN': 'Non-Playable Airliner',
			'DEADDODO': 'Non-Playable Dodo',
			'SPEEDER': 'Speeder',
			'REEFER': 'Reefer',
			'PANLANT': 'Panlantic',
			'FLATBED': 'Flatbed',
			'YANKEE': 'Yankee',
			'BORGNINE': 'Borgnine Cabbie'
		}
	},
	GTAVC: {
		METHOD: 'GET',
		DATA_URL: 'models/gta_vc.json',
		IMAGES_URL: 'img/vehicles/gta_vc',
		START_INDEX: 0,
		PARAMETER_NAMES: {
			id: 'Vehicle Id',
			mass: 'Mass',
			dimx: 'Dimension: X Axis',
			dimy: 'Dimension: Y Axis',
			dimz: 'Dimension: Z Axis',
			cmassx: 'Center of Mass: X Axis',
			cmassy: 'Center of Mass: Y Axis',
			cmassz: 'Center of Mass: Z Axis',
			persubmerged: 'Percent Submerged',
			tractionmult: 'Traction: Multiplier',
			tractionloss: 'Traction: Loss',
			tractionbias: 'Traction: Bias',
			numofgears: 'Number of Gears',
			velocity: 'Velocity',
			acceleration: 'Acceleration',
			drivetype: 'Drive Type',
			enginetype: 'Engine Type',
			deceleration: 'Deceleration',
			brakebias: 'Brake Bias',
			abs: 'ABS',
			steeringlock: 'Steering Lock',
			suspensionforce: 'Suspension: Force',
			suspensiondamping: 'Suspension: Damping',
			seatoffset: 'Seat Offset',
			collisiondamage: 'Collision Damage',
			value: 'Monetary Value',
			suspensionuplimit: 'Suspension: Upper Limit',
			suspensionlowlimit: 'Suspension: Lower Limit',
			suspensionbias: 'Suspension: Bias',
			suspensionantidive: 'Suspension: Anti-Dive',
			flags: 'Flags',
			frontlights: 'Front Lights',
			rearlights: 'Rear Lights'
		},
		VEHICLE_NAMES: {
			'LANDSTAL': 'Landstalker',
			'IDAHO': 'Idaho',
			'STINGER': 'Stinger',
			'LINERUN': 'Linerunner',
			'PEREN': 'Perennial',
			'SENTINEL': 'Sentinel',
			'PATRIOT': 'Patriot',
			'FIRETRUK': 'Fire Truck',
			'TRASH': 'Trashmaster',
			'STRETCH': 'Stretch',
			'MANANA': 'Manana',
			'INFERNUS': 'Infernus',
			'PONY': 'Pony',
			'MULE': 'Mule',
			'CHEETAH': 'Cheetah',
			'AMBULAN': 'Ambulance',
			'FBICAR': 'FBI Car',
			'MOONBEAM': 'Moonbeam',
			'ESPERANT': 'Esperanto',
			'TAXI': 'Taxi',
			'KURUMA': 'Kuruma',
			'BOBCAT': 'Bobcat',
			'MRWHOOP': 'Mr. Whoopie',
			'BFINJECT': 'BF Injection',
			'POLICE': 'Police',
			'ENFORCER': 'Enforcer',
			'SECURICA': 'Securicar',
			'BANSHEE': 'Banshee',
			'PREDATOR': 'Predator',
			'BUS': 'Bus',
			'RHINO': 'Rhino',
			'BARRACKS': 'Barracks OL',
			'TRAIN': 'Train',
			'HELI': 'Police Heli',
			'DODO': 'Dodo',
			'COACH': 'Coach',
			'CABBIE': 'Cabbie',
			'STALLION': 'Stallion',
			'RUMPO': 'Rumpo',
			'RCBANDIT': 'RC Bandit',
			'BELLYUP': 'Belly Up',
			'MRWONGS': 'Mr. Wong\'s',
			'MAFIA': 'Mafia Sentinel',
			'YARDIE': 'Yardie Lobo',
			'YAKUZA': 'Yakuza Stinger',
			'DIABLOS': 'Diablo Stallion',
			'COLUMB': 'Cartel Cruiser',
			'HOODS': 'Hoods Rumpo',
			'AIRTRAIN': 'Non-Playable Airliner',
			'DEADDODO': 'Non-Playable Dodo',
			'SPEEDER': 'Speeder',
			'REEFER': 'Reefer',
			'PANLANT': 'Panlantic',
			'FLATBED': 'Flatbed',
			'YANKEE': 'Yankee',
			'GOLFCART': 'Caddie',
			'VOODOO': 'Voodoo',
			'WASHING': 'Washington',
			'CUBAN': 'Cuban Hermes',
			'ROMERO': 'Romero\'s Hearse',
			'PACKER': 'Packer',
			'ADMIRAL': 'Admiral',
			'GANGBUR': 'Gang Burrito',
			'ZEBRA': 'Zebra',
			'TOPFUN': 'Top Fun',
			'GLENDALE': 'Glendale',
			'OCEANIC': 'Oceanic',
			'HERMES': 'Hermes',
			'SABRE1': 'Sabre',
			'SABRETUR': 'Sabre Turbo',
			'PHEONIX': 'Phoenix',
			'WALTON': 'Walton',
			'REGINA': 'Regina',
			'COMET': 'Comet',
			'DELUXO': 'Deluxo',
			'BURRITO': 'Burrito',
			'SPAND': 'Spand Express',
			'BAGGAGE': 'Baggage Handler',
			'KAUFMAN': 'Kaufman Cab',
			'RANCHER': 'Rancher',
			'FBIRANCH': 'FBI Rancher',
			'VIRGO': 'Virgo',
			'GREENWOO': 'Greenwood',
			'HOTRING': 'Hotring Racer',
			'SANDKING': 'Sandking',
			'BLISTAC': 'Blista Compact',
			'BOXVILLE': 'Boxville',
			'BENSON': 'Benson',
			'DESPERAD': 'Mesa Grande',
			'LOVEFIST': 'Love Fist',
			'BLOODRA': 'Bloodring Banger A',
			'BLOODRB': 'Bloodring Banger B',
			'BIKE': 'PCJ-600',
			'MOPED': 'Faggio',
			'DIRTBIKE': 'Sanchez',
			'ANGEL': 'Angel',
			'FREEWAY': 'Freeway',
			'PREDATOR': 'Predator',
			'SPEEDER': 'Speeder',
			'REEFER': 'Reefer',
			'RIO': 'Rio',
			'SQUALO': 'Squalo',
			'TROPIC': 'Tropic',
			'COASTGRD': 'Coast Guard',
			'DINGHY': 'Dinghy',
			'MARQUIS': 'Marquis',
			'CUPBOAT': 'Jetmax',
			'SEAPLANE': 'Seaplane',
			'SPARROW': 'Sparrow',
			'SEASPAR': 'Sea Sparrow',
			'MAVERICK': 'Maverick',
			'COASTMAV': 'Coast Guard Maverick',
			'POLMAV': 'Police Maverick',
			'HUNTER': 'Hunter',
			'RCBARON': 'RC Baron',
			'RCGOBLIN': 'RC Goblin',
			'RCCOPTER': 'RC Copter'
		}
	}
};